dist: xenial
language: node_js
node_js: lts/*

cache: yarn

addons:
  firefox: latest
  chrome: stable
  apt:
    packages:
      - fluxbox

services:
  - xvfb

script: yarn run test:gh-pages

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: dist_gh_pages
    on:
      branch: master
