dist: xenial
language: node_js
node_js: lts/*

cache: yarn

addons:
  firefox: latest
  chrome: stable
  apt:
    packages:
      - fluxbox

before_install:
- stty cols 80

services:
  - xvfb

before_script:
- fluxbox >/dev/null 2>&1 &

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn run build:gh-pages; fi

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: dist_gh_pages
    on:
      branch: master
