dist: xenial
language: node_js
node_js: lts/*

cache: yarn

addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable fluxbox

before_install:
- stty cols 80

services:
  - xvfb

before_script:
- fluxbox >/dev/null 2>&1 &