version: '3'
services:
  front:
    build: ./frontend
    volumes:
      - ./frontend:/app
    environment:
      API_HOST: api
    ports:
      - "8080:8080"
  api:
    build: ./api
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    environment:
      - SECRET_KEY_BASE=mysecretkey
      - POSTGRES_PASSWORD
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
