version: '3'
services:
  front:
    build:
      context: ./frontend
      dockerfile: tests/docker/Dockerfile
    ports:
      - "80:80"
  api:
    build:
      context: ./api
      args:
        RAILS_ENV: production
    environment:
      - SECRET_KEY_BASE=mysecretkey
      - POSTGRES_PASSWORD
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD
