version: '3'
services:
  front:
    build:
      context: ./frontend
      dockerfile: production/Dockerfile
    volumes:
      - ./frontend/tests/e2e/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
  api:
    build:
      context: ./api
      args:
        RAILS_ENV: production
    environment:
      - SECRET_KEY_BASE=mysecretkey
      - POSTGRES_PASSWORD=mypostgrespassword
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mypostgrespassword
