version: '3'
services:
  front:
    build:
      context: ./frontend
      dockerfile: production/Dockerfile
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "443:443"
  api:
    build:
      context: ./api
      args:
        RAILS_ENV: production
    ports:
      - "3000:3000"
    environment:
      - SECRET_KEY_BASE
      - POSTGRES_PASSWORD
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - ./db:/var/lib/postgresql/data