version: '3'
services:
  front:
    build:
      context: ./frontend
      dockerfile: production/Dockerfile
    volumes:
      - ./frontend/production/nginx:/etc/nginx/conf.d
      - ./frontend/production/certbot/conf:/etc/letsencrypt
      - ./frontend/production/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  api:
    build:
      context: ./api
      args:
        RAILS_ENV: production
    environment:
      - SECRET_KEY_BASE
      - POSTGRES_PASSWORD
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - ./db:/var/lib/postgresql/data
  certbot:
    image: certbot/certbot
    volumes:
      - ./frontend/production/certbot/conf:/etc/letsencrypt
      - ./frontend/production/certbot/www:/var/www/certbot
    restart: unless-stopped
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"