version: 2
jobs:
  test:
    working_directory: /app
    docker:
    - image: docker:stable
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build test Docker image
        command: |
          docker build \
                 -f docker/Dockerfile \
                 -t listvue-test \
                 .
    - run:
        name: Run package audit, lint, and unit tests
        command: |
          docker run -i --rm \
                 listvue-test \
                 sh -c 'yarn run audit:packages && yarn run lint && yarn run test:unit'
    - run:
        name: Build production Docker image
        command: |
          docker build \
                 -f docker/Dockerfile.production \
                 -t listvue-prod \
                 .
    - run:
        name: Run production Docker container
        command: |
          docker run -i --rm \
                 -p 8080:80 \
                 --name listvue-prod \
                 listvue-prod
        background: true
    - run:
        name: Build TestCafé image
        command: |
          docker build \
                 -f docker/Dockerfile.testcafe \
                 -t listvue-testcafe \
                 .
    - run:
        name: Run TestCafé against production container
        command: |
          docker run -i --rm \
                 --net="host" \
                 listvue-testcafe 'chromium --no-sandbox,firefox' /tests
    - run:
        name: Stop production Docker contianer
        command: docker stop listvue-prod

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - gh-pages
