version: 2
jobs:
  build:
    working_directory: /app
    docker:
    - image: docker:stable
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build test Docker image
        command: |
          docker build \
                 -f docker/Dockerfile \
                 -t list-vue-test \
                 .
    - run:
        name: Run lint and unit tests
        command: |
          docker run -i --rm \
                 list-vue-test \
                 sh -c 'yarn run audit:packages && yarn run lint && yarn run test:unit'
    - run:
        name: Build production Docker image
        command: |
          docker build \
                 -f docker/Dockerfile.production \
                 -t list-vue-prod \
                 .
    - run:
        name: Run production Docker container
        command: |
          docker run -i --rm \
                 -p 8080:80 \
                 --name list-vue-prod \
                 list-vue-prod
        background: true
    - run:
        name: Build TestCafé image
        command: |
          docker build \
                 -f docker/Dockerfile.testcafe \
                 -t todo-testcafe \
                 .
    - run:
        name: Run TestCafé against production container
        command: |
          docker run -i --rm \
                 --net="host" \
                 todo-testcafe 'chromium --no-sandbox,firefox' /tests
    - run:
        name: Stop production Docker contianer
        command: docker stop list-vue-prod
