version: 2
jobs:
  build:
    working_directory: /app
    docker:
    - image: docker:stable
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Install dependencies
        command: |
          apk update && apk add --no-cache bash curl
    - run:
        name: Build test Docker image
        command: |
          docker build \
                 -f docker/Dockerfile \
                 -t todo-vue-test \
                 .
    - run:
        name: Run lint and unit tests
        command: |
          docker run -i --rm \
                 todo-vue-test \
                 sh -c 'yarn run lint && yarn run test:unit'
    - run:
        name: Build production Docker image
        command: |
          docker build \
                 -f docker/Dockerfile.production \
                 -t todo-vue-prod \
                 .
    - run:
        name: Run production Docker container
        command: |
          docker run -i --rm \
                 -p 8080:80 \
                 --name todo-vue-prod \
                 todo-vue-prod
        background: true
    - run:
        name: Run TestCafé against production container
        command: |
          docker run -i --rm \
                     -v `pwd`/tests/e2e:/tests \
                     --net="host" \
                     testcafe/testcafe 'chromium --no-sandbox,firefox' /tests
    - run:
        name: Stop production Docker contianer
        command: docker stop todo-vue-prod