version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Run frontend package audit, lint, and unit tests
          command: ./frontend/tests/run.sh
      - run:
          name: Deloy production application in Docker containers
          command: |
            set -x
            docker-compose -f docker-compose-test.yml --project-name listvue up --build -d
            docker build -t wait wait && docker run -it --rm --network="listvue_default" wait api:3000
            ./api/setup_db.sh
      - run:
          name: Run E2E tests
          command: ./frontend/tests/e2e/run.sh
      - run:
          name: Stop production Docker deployment
          command: docker-compose --project-name listvue down
